- name: get certs.pem
  stat:
    path: "/etc/letsencrypt/live/{{ domain_name }}/{{ item }}"
    get_attributes: no
  register: cert_answer
  loop:
    - cert.pem
    - privkey.pem
    - fullchain.pem
- name: initialize
  set_fact:
    ssl_certificates: []
- name: aggregate certs
  set_fact:
    ssl_certificates: "{{ ssl_certificates + [item.stat.lnk_source + ':/certs/' + item.item] }}"
    no_log: True
  loop: "{{ cert_answer.results }}"

- name: append to nginx_volumes
  set_fact:
    nginx_volumes: "{{ nginx_volumes + ssl_certificates }}"
