- name: include cert.yml tasks
  include_tasks: cert.yml
  when: domain_name is defined
- name: create dir
  file:
    state: directory
    path: /var/lib/guov/nginx
- name: send template
  template:
    src: nginx.conf
    dest: /var/lib/guov/nginx/nginx.conf
- name: debug
  debug:
    msg: "{{ nginx_volumes }}"
- name: start container
  docker_container:
    name: nginx
    image: nginx
    volumes: "{{ nginx_volumes }}"
    network_mode: host
    restart_policy: always
    restart: yes
    recreate: yes
    state: started
