- name: create dir
  file:
    state: directory
    path: /var/lib/guov/nginx
- name: send template
  template:
    src: nginx.conf
    dest: /var/lib/guov/nginx/nginx.conf
- name: start container
  docker_container:
    name: nginx
    image: nginx
    volumes:
      - /var/lib/guov/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/dev.scis.xyz/:/certs/
      - "frontend_static{{ hostvars['localhost']['last_commit'] }}:/app/static"
    network_mode: host
    restart_policy: always
    restart: yes
    recreate: yes
    state: started
