- hosts: domain
  gather_facts: no
  tasks:
    - name: get cert.pem
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}/cert.pem"
      register: cert_answer 
    - name: get privkey.pem 
      stat:
        path: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"
      register: privkey_answer
    - name: make it fact
      set_fact:
        cert_pem_path: "{{ cert_answer.stat.lnk_source }}"
        priv_key_path: "{{ privkey_answer.stat.lnk_source }}"
    - name: debug
      debug:
        msg: "{{ cert_pem_path }} {{ priv_key_path }} {{ domain_name }}"

