- hosts: local
  gather_facts: no
  roles:
    - role: git
      vars:
        - repo_url: frontstimul
    - frontend_build
- hosts: astra1
  gather_facts: no
  roles:
    - frontend_deploy
    - nginx
