- hosts: localhost
  vars_files: 
    - passwords.yml

  tasks:
    - name: clone git repository
      git:
        repo: ssh://git@bitbucket.org/guov/guov-kanban-back.git
        dest: /tmp/test/backend
        depth: 1
      register: gitResult
    - name: Docker login
      docker_login:
        registry: docker.scis.xyz
        username: developer
        password: "{{ docker_registry_password }}"
    - name: build docker image
      docker_image:
        name: docker.scis.xyz/devops-test
        state: present
        tag: "{{ gitResult.after }}"
        path: /tmp/test/backend
        push: true
      register: docker_image_result