- hosts: localhost
  tasks:
    - name: clone git repository
      git:
        repo: ssh://git@bitbucket.org/guov/guov-kanban-back.git
        dest: /tmp/test/backend
        depth: 1
        version: task_priority
      register: gitResult

- hosts: astra1
  vars_files:
  - passwords.yml
  vars:
    gitResult: "{{ hostvars['localhost']['gitResult'] }}"

  tasks:
  - name: login to registry
    docker_login:
      registry: docker.scis.xyz
      username: developer
      password: "{{ docker_registry_password }}"
      state: present
  - name: pull image
    docker_image:
      name: docker.scis.xyz/kanban-backend
      tag: "{{ gitResult.after }}"
      state: present

  - name: run migrations
    docker_container:
      name: migrations
      state: started
      image: "docker.scis.xyz/kanban-backend:{{ gitResult.after }}"
      detach: no
      network_mode: host
      recreate: true
      command: npm run migrate:up
      env_file: /var/lib/guov/backend/.env

  - name: start container
    docker_container:
      name: backend_all
      state: started
      image: "docker.scis.xyz/kanban-backend:{{ gitResult.after }}"
      network_mode: host
      restart_policy: always
      recreate: true
      env_file: /var/lib/guov/backend/.env

  - name: logout from docker registry
    docker_login:
      registry: docker.scis.xyz
      state: absent