- name: .env
  template:
    src: env.secret
    dest: /var/lib/guov/backend/.env
- name: login to registry
  docker_login:
    registry: docker.scis.xyz
    username: "{{ docker_login }}"
    password: "{{ docker_password }}"
    state: present
- name: pull image
  docker_image:
    name: docker.scis.xyz/kanban-backend
    tag: "{{ hostvars['localhost']['last_commit'] }}"
    state: present

- name: run migrations
  docker_container:
    name: migrations
    state: started
    image: "docker.scis.xyz/kanban-backend:{{ hostvars['localhost']['last_commit'] }}"
    detach: no
    network_mode: host
    recreate: true
    command: npm run migrate:up
    env_file: /var/lib/guov/backend/.env

- name: start container
  docker_container:
    name: backend_all
    state: started
    image: "docker.scis.xyz/kanban-backend:{{ hostvars['localhost']['last_commit'] }}"
    network_mode: host
    restart_policy: always
    recreate: true
    env_file: /var/lib/guov/backend/.env

- name: logout from docker registry
  docker_login:
    registry: docker.scis.xyz
    state: absent