- name: Docker login
  docker_login:
    registry: docker.scis.xyz
    username: "{{ docker_login }}"
    password: "{{ docker_password }}"
    state: present
- name: build docker image
  docker_image:
    name: docker.scis.xyz/backend
    state: present
    tag: "{{ hostvars.localhost.last_commit }}"
    path: /var/lib/guov/backstimul
    push: true
  register: built_image
- name: clear all old images
  shell: "docker images | grep backend | grep -v {{ hostvars.localhost.last_commit }} | awk '{ print $3 }' | xargs docker rmi -f || true"
