# git уже склонирован
- name: build front image
  docker_image:
    name: docker.scis.xyz/stimul_front
    state: present
    tag: "{{ hostvars['localhost']['last_commit'] }}"
    path: /var/lib/guov/stimul/client
    push: no
- name: build front static files
  docker_container:
    name: build_front
    image: "docker.scis.xyz/stimul_front:{{ hostvars['localhost']['last_commit'] }}"
    state: started
    detach: no
    env:
      REACT_APP_ENDPOINT: localhost:8500
    volumes:
      /var/lib/guov/frontend_static:/app/build

