- name: container
  docker_container:
    image: mongo:4
    name: mongo
    volumes:
      /var/lib/guov/mongo/data:/data/db
    env:
      MONGO_INITDB_ROOT_USERNAME: "{{ mongo_user }}"
      MONGO_INITDB_ROOT_PASSWORD: "{{ mongo_password }}"
    restart_policy: unless-stopped
    ports:
      "{{ mongo_port }}:27017"
