- name: .env
  template:
    src: env.secret
    dest: /var/lib/guov/backend/.env

- name: login to registry
  docker_login:
    registry: docker.scis.xyz
    username: "{{ docker_login }}"
    password: "{{ docker_password }}"
    state: present

- name: pull image
  docker_image:
    name: docker.scis.xyz/backend
    tag: "{{ hostvars.localhost.last_commit }}"
    state: present

- name: start container
  docker_container:
    name: "backend_linter"
    state: started
    image: "docker.scis.xyz/backend:{{ hostvars.localhost.last_commit }}"
    detach: no 
    command: npm run lint 
    recreate: yes
  register: result

- name: docker system prune -f
  shell: docker system prune -f

- name: clear all old images
  shell: "docker images | grep backend | grep -v {{ hostvars.localhost.last_commit }} | awk '{ print $3 }' | xargs docker rmi -f || true"

# - name: logout from docker registry
#   docker_login:
#     registry: docker.scis.xyz
#     state: absent
