- name: Create directory
  file:
    path: /var/lib/guov
    state: directory
- name: git clone
  git:
    repo: ssh://git@bitbucket.org/guov/stimul.git
    dest: /var/lib/guov/stimul
    depth: 1
    version: delivered
  register: git_result
- name: last commit
  set_fact:
    last_commit: "{{ git_result['after'][0:8] }}"
