- name: Create directory
  file:
    path: /var/lib/guov
    state: directory
- name: git clone
  git:
    repo: ssh://git@bitbucket.org/guov/stimul.git
    dest: /var/lib/guov/stimul
    depth: 1
    version: "{{ lookup('env','BRANCH') | default('dev', true) }}"
  register: git_result
- name: last commit
  set_fact:
    last_commit: "{{ git_result['after'][0:8] }}"
- name: last commit message
  shell: "git log --pretty=\"author: %an, message: '%s', %ar\" -n1"
  args:
    chdir: /var/lib/guov/stimul
  register: latest_commit_message
- name: debug git clone
  debug:
    msg: 
      - "branch: {{ lookup('env','BRANCH') | default('dev', true) }}"
      - "commit hash: {{ last_commit }}"
      - "{{ latest_commit_message.stdout }}"

