- name: git clone
  git:
    repo: "ssh://git@bitbucket.org/guov/{{ repo_url }}.git"
    dest: "/var/lib/guov/{{ repo_url }}"
    depth: 1
    version: "{{ lookup('env','BRANCH') | default('master', true) }}"
    force: true
  register: git_result
- name: last commit
  set_fact:
    last_commit: "{{ git_result.after }}"
- name: last commit message
  shell: "git log --pretty=\"author: %an, message: '%s', %ar\" -n1"
  args:
    chdir: "/var/lib/guov/{{ repo_url }}"
  register: latest_commit_message
- name: debug git clone
  debug:
    msg: 
      - "branch: {{ lookup('env','BRANCH') | default('master', true) }}"
      - "commit hash: {{ last_commit }}"
      - "{{ latest_commit_message.stdout }}"
