- name: Docker login
  docker_login:
    registry: docker.scis.xyz
    username: "{{ docker_login }}"
    password: "{{ docker_password }}"
    state: present
- name: template .env
  template:
    src: .env
    dest: /var/lib/guov/frontstimul/.env
- name: build front image
  docker_image:
    name: docker.scis.xyz/stimul_busybox
    state: present
    tag: "{{ hostvars.localhost.last_commit }}"
    path: /var/lib/guov/frontstimul
    push: yes
- name: clear all old images
  shell: "docker images | grep frontstimul | grep stimul_busybox | grep -v {{ hostvars.localhost.last_commit }} | awk '{ print $3 }' | xargs docker rmi -f || true"
