- name: Docker login
  docker_login:
    registry: docker.scis.xyz
    username: "{{ docker_login }}"
    password: "{{ docker_password }}"
    state: present
- name: build front image
  docker_image:
    name: docker.scis.xyz/stimul_front
    state: present
    tag: "{{ hostvars['localhost']['last_commit'] }}"
    path: /var/lib/guov/stimul/client
    push: no
- name: build front static files
  docker_container:
    name: build_front
    image: "docker.scis.xyz/stimul_front:{{ hostvars['localhost']['last_commit'] }}"
    state: started
    detach: no
    env:
      REACT_APP_ENDPOINT: 185.168.187.103:8500
    volumes:
      /var/lib/guov/frontend_static:/app/static
- name: busybox with frontend static
  docker_image:
    name: docker.scis.xyz/stimul_busybox
    state: present
    tag: "{{ hostvars['localhost']['last_commit'] }}"
    path: /var/lib/guov/frontend_static
    dockerfile: /var/lib/guov/stimul/client/busybox.Dockerfile
    push: yes

