- name: http request to bitbucket
  uri:
    url: "https://api.bitbucket.org/2.0/repositories/guov/backstimul/commit/{{ last_commit if last_commit is defined else hostvars.localhost.last_commit }}/statuses/build"
    headers:
      Authorization: "Basic aWxudXJpYmF0OlhoU1BLNHNtRnBUajMyN2dBVERR"
    status_code:
      - 200
      - 201
    method: POST
    body_format: json
    body:
      state: "{{ build_state }}"
      key: "{{ build_key }}"
      url: "{{ build_url | default('https://ci.scis.xyz#incorrect') }}"
      name: "{{ build_name }}"
      description: "{{ build_description | default('default description')}}"
    return_content: yes
  register: response
