- name: Docker login
  docker_login:
    registry: docker.scis.xyz
    username: "{{ docker_login }}"
    password: "{{ docker_password }}"
- name: build docker image
  docker_image:
    name: docker.scis.xyz/stimul
    state: present
    tag: "{{ hostvars['localhost']['last_commit'] }}"
    path: /var/lib/guov/stimul
    push: true
  register: docker_image_result
